apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: issues
  name: issues
  namespace: aybaze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issues
  template:
    metadata:
      labels:
        app: issues
    spec:
      containers:
        - image: aybaze/issues:$TAG
          imagePullPolicy: Always
          name: issues
          env:
            - name: ISSUES_POSTGRES
              value: issues-postgres
          volumeMounts:
            - name: keys
              mountPath: /usr/aybaze/keys
              readOnly: true
          volumeMounts:
            - name: config
              mountPath: /usr/aybaze/config
              readOnly: true
          ports:
            - containerPort: 8000
              protocol: TCP
      volumes:
        - name: config
          secret:
            secretName: config-secret
            items:
              - key: config-production.yaml
                path: config.yaml
        - name: keys
          secret:
            secretName: issues-keys
            items:
              - key: 2019-10-26.private-key.pem
                path: 2019-10-26.private-key.pem               
---
apiVersion: v1
kind: Service
metadata:
  name: issues
  namespace: aybaze
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: issues
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
  name: issues
  namespace: aybaze
spec:
  rules:
    - host: issues.aybaze.com
      http:
        paths:
          - backend:
              serviceName: issues
              servicePort: 8000
            path: /
  tls:
    - hosts:
        - issues.aybaze.com
      secretName: issues-tls
